#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo '***************************************************'
echo '********************注意提交格式*******************'
echo '***************************************************'
echo 'git commit -m <type>[optional scope]: <description>'
echo '***************************************************
          'feat'：     新功能 feature
          'fix'：      修复 bug
          'docs'：     文档注释
          'style'：    代码格式(不影响代码运行的变动)
          'refactor'： 重构(既不增加新功能，也不是修复bug)
          'perf'：     性能优化
          'test'：     增加测试
          'chore'：    构建过程或辅助工具的变动
          'revert'：   回退
          'build'：    打包'
echo '***************************************************'
npx lint-staged --allow-empty
